server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true


rsa:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
spring:
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url:  jdbc:oracle:thin:@localhost:1521/kda_pdb
    username: kda
    password: 123
  flyway:
    url: jdbc:oracle:thin:@localhost:1521/kda_pdb
    locations: classpath:db/migration
    user: kda
    password: 123
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:

      hibernate:

        dialect: org.hibernate.dialect.OracleDialect

    hibernate:
      ddl-auto: validate


jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 36000000
  issuer: proselyte
qr:
  client-url: http://localhost:3000/qrcode